################################################################################
# MEDIA STACK => docker compose -f stacks/media/jellyfin.yaml up -d
################################################################################

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.1
    restart: unless-stopped
    labels:
      sablier.enable: "true"
      sablier.group: jellyfin
      traefik.enable: "true"
      traefik.swarm.lbswarm: "true"
      traefik.http.routers.jellyfin.middlewares: jellyseerr@swarm
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.lsarlinmagnus.fr`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.tls.certresolver: ovh
      homepage.group: Media
      homepage.name: Jellyfin
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.lsarlinmagnus.fr
      homepage.widget.type: jellyfin
      homepage.widget.url: http://jellyfin:8096
      homepage.widget.key: ${JELLYFIN_HOMEPAGE_API_KEY}
      homepage.widget.enableBlocks: "true"
      homepage.widget.enableNowPlaying: "true"
      homepage.widget.fields: '["movies", "series", "episodes"]'
    environment:
      TZ: Europe/Paris
    volumes:
      - /media/raid/jellyfin/media/audiobooks:/data/audiobooks
      - /media/raid/jellyfin/media/movies:/data/movies
      - /media/raid/jellyfin/media/series:/data/series
      - media_jellyfin_config:/config
    networks:
      - proxy
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  media_jellyfin_config:
    external: true

networks:
  proxy:
    external: true