################################################################################
# MEDIA STACK => docker stack deploy -c stacks/media/stack.yaml media
################################################################################

version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    deploy:
      replicas: 1
      labels:
        - homepage.group=Media
        - homepage.name=Jellyfin
        - homepage.icon=jellyfin.png
    # volumes:
    #   - /path/to/config:/config
    #   - /path/to/cache:/cache
    #   - type: bind
    #     source: /path/to/media
    #     target: /media
    #   - type: bind
    #     source: /path/to/media2
    #     target: /media2
    #     read_only: true
    #   # Optional - extra fonts to be used during transcoding with subtitle burn-in
    #   - type: bind
    #     source: /path/to/fonts
    #     target: /usr/local/share/fonts/custom
    #     read_only: true
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    # # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    # user: 1000:1000
    ports:
      - 3010:8096/tcp
      - 3011:7359/udp
    healthcheck:
      disable: false
    networks:
      - overlay_net

networks:
  overlay_net:
    driver: overlay
    attachable: true