################################################################################
# MEDIA STACK => docker stack deploy -c stacks/media/stack.yaml media
################################################################################

version: '3.8'

services:
  radarr:
    image: linuxserver/radarr:6.0.4
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.radarr.loadbalancer.server.port: 7878
        traefik.http.routers.radarr.rule: Host(`radarr.lsarlinmagnus.fr`)
        traefik.http.routers.radarr.entrypoints: websecure
        traefik.http.routers.radarr.tls: "true"
        traefik.http.routers.radarr.tls.certresolver: ovh
        traefik.http.routers.radarr.middlewares: authelia@file
        wud.tag.include: ^\d+\.\d+\.\d+$$
    configs:
      - source: radarr_config
        target: /config/config.xml
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - radarr_data:/config
      - /media/raid/transmission/downloads/complete/radarr:/downloads/complete/radarr
      - /media/raid/jellyfin/media/movies:/movies
    networks:
      - proxy

  sonarr:
    image: linuxserver/sonarr:4.0.16
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.sonarr.loadbalancer.server.port: 8989
        traefik.http.routers.sonarr.rule: Host(`sonarr.lsarlinmagnus.fr`)
        traefik.http.routers.sonarr.entrypoints: websecure
        traefik.http.routers.sonarr.tls: "true"
        traefik.http.routers.sonarr.tls.certresolver: ovh
        traefik.http.routers.sonarr.middlewares: authelia@file
        wud.tag.include: ^\d+\.\d+\.\d+$$
    configs:
      - source: sonarr_config
        target: /config/config.xml
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - sonarr_data:/config
      - /media/raid/transmission/downloads/complete/tv-sonarr:/downloads/complete/tv-sonarr
      - /media/raid/jellyfin/media/series:/tvshows
    networks:
      - proxy

  transmission:
    image: linuxserver/transmission:4.0.6
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.transmission.loadbalancer.server.port: 9091
        traefik.http.routers.transmission.rule: Host(`transmission.lsarlinmagnus.fr`)
        traefik.http.routers.transmission.entrypoints: websecure
        traefik.http.routers.transmission.tls: "true"
        traefik.http.routers.transmission.tls.certresolver: ovh
        traefik.http.routers.transmission.middlewares: authelia@file
        wud.tag.include: ^\d+\.\d+\.\d+$$
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - transmission_data:/config
      - /media/raid/transmission/downloads:/downloads
    networks:
      - proxy

  jackett:
    image: linuxserver/jackett:0.24.850
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.jackett.loadbalancer.server.port: 9117
        traefik.http.routers.jackett.rule: Host(`jackett.lsarlinmagnus.fr`)
        traefik.http.routers.jackett.entrypoints: websecure
        traefik.http.routers.jackett.tls: "true"
        traefik.http.routers.jackett.tls.certresolver: ovh
        traefik.http.routers.jackett.middlewares: authelia@file
        wud.tag.include: ^\d+\.\d+\.\d+$$
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - jackett_data:/config
      - /media/raid/jackett/downloads:/downloads
    networks:
      - proxy

  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
        traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.lsarlinmagnus.fr`)
        traefik.http.routers.jellyseerr.entrypoints: websecure
        traefik.http.routers.jellyseerr.tls: "true"
        traefik.http.routers.jellyseerr.tls.certresolver: ovh
        wud.tag.include: ^\d+\.\d+\.\d+$$
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - jellyseerr_data:/app/config
    networks:
      - proxy

configs:
  radarr_config:
    file: ./config/radarr/config.xml
  sonarr_config:
    file: ./config/sonarr/config.xml

volumes:
  radarr_data:
  sonarr_data:
  transmission_data:
  jackett_data:
  jellyseerr_data:

networks:
  proxy:
    external: true