################################################################################
# MEDIA STACK => docker stack deploy -c stacks/media/stack.yaml media
################################################################################

version: '3.8'

services:
  radarr:
    image: linuxserver/radarr:6.0.4
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.radarr.loadbalancer.server.port: 7878
        traefik.http.routers.radarr.rule: Host(`radarr.lsarlinmagnus.fr`)
        traefik.http.routers.radarr.entrypoints: websecure
        traefik.http.routers.radarr.tls: "true"
        traefik.http.routers.radarr.tls.certresolver: ovh
        traefik.http.routers.radarr.middlewares: authelia@file
        homepage.group: Media
        homepage.name: Radarr
        homepage.icon: radarr.png
        homepage.href: https://radarr.lsarlinmagnus.fr
        homepage.widget.type: radarr
        homepage.widget.url: http://radarr:7878
        homepage.widget.key: ${RADARR_HOMEPAGE_API_KEY}
        homepage.widget.fields: '["wanted", "missing", "queued", "movies"]'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /media/raid/radarr/config:/config
      - /media/raid:/media/raid
    networks:
      - proxy

  sonarr:
    image: linuxserver/sonarr:4.0.16
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.sonarr.loadbalancer.server.port: 8989
        traefik.http.routers.sonarr.rule: Host(`sonarr.lsarlinmagnus.fr`)
        traefik.http.routers.sonarr.entrypoints: websecure
        traefik.http.routers.sonarr.tls: "true"
        traefik.http.routers.sonarr.tls.certresolver: ovh
        traefik.http.routers.sonarr.middlewares: authelia@file
        homepage.group: Media
        homepage.name: Sonarr
        homepage.icon: sonarr.png
        homepage.href: https://sonarr.lsarlinmagnus.fr
        homepage.widget.type: sonarr
        homepage.widget.url: http://sonarr:8989
        homepage.widget.key: ${SONARR_HOMEPAGE_API_KEY}
        homepage.widget.fields: '["wanted", "queued", "series"]'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /media/raid/sonarr/config:/config
      - /media/raid:/media/raid
    networks:
      - proxy

  transmission:
    image: linuxserver/transmission:4.1.0
    labels:
      wud.tag.include: ^\d\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.transmission.loadbalancer.server.port: 9091
        traefik.http.routers.transmission.rule: Host(`transmission.lsarlinmagnus.fr`)
        traefik.http.routers.transmission.entrypoints: websecure
        traefik.http.routers.transmission.tls: "true"
        traefik.http.routers.transmission.tls.certresolver: ovh
        traefik.http.routers.transmission.middlewares: authelia@file
        homepage.group: Media
        homepage.name: Transmission
        homepage.icon: transmission.png
        homepage.href: https://transmission.lsarlinmagnus.fr
        homepage.widget.type: transmission
        homepage.widget.url: http://transmission:9091
        homepage.widget.rpcURL: /transmission/
        homepage.widget.fields: '["leech", "download", "seed", "upload"]'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /media/raid/transmission/config:/config
      - /media/raid/transmission/downloads:/media/raid/transmission/downloads
    networks:
      - proxy

  jackett:
    image: linuxserver/jackett:0.24.1140
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.jackett.loadbalancer.server.port: 9117
        traefik.http.routers.jackett.rule: Host(`jackett.lsarlinmagnus.fr`)
        traefik.http.routers.jackett.entrypoints: websecure
        traefik.http.routers.jackett.tls: "true"
        traefik.http.routers.jackett.tls.certresolver: ovh
        traefik.http.routers.jackett.middlewares: authelia@file
        homepage.group: Media
        homepage.name: Jackett
        homepage.icon: jackett.png
        homepage.href: https://jackett.lsarlinmagnus.fr
        homepage.widget.type: jackett
        homepage.widget.url: http://jackett:9117
        homepage.widget.fields: '["configured", "errored"]'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /media/raid/jackett/config:/config
      - /media/raid/jackett/downloads:/downloads
    networks:
      - proxy

  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        sablier.enable: "true"
        sablier.group: jellyseerr
        traefik.enable: "true"
        traefik.swarm.lbswarm: "true"
        traefik.http.routers.jellyseerr.middlewares: jellyseerr@swarm
        traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
        traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.lsarlinmagnus.fr`)
        traefik.http.routers.jellyseerr.entrypoints: websecure
        traefik.http.routers.jellyseerr.tls: "true"
        traefik.http.routers.jellyseerr.tls.certresolver: ovh
        homepage.group: Media
        homepage.name: Jellyseerr
        homepage.icon: jellyseerr.png
        homepage.href: https://jellyseerr.lsarlinmagnus.fr
        homepage.widget.type: jellyseerr
        homepage.widget.url: http://jellyseerr:5055
        homepage.widget.key: ${JELLYSEERR_HOMEPAGE_API_KEY}
        homepage.widget.fields: '["pending", "approved", "available", "issues"]'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    volumes:
      - /media/raid/jellyseerr/config:/app/config
    networks:
      - proxy

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    labels:
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        homepage.group: Media
        homepage.name: Flaresolverr
        homepage.icon: flaresolverr.png
    environment:
      LOG_LEVEL: info
      TZ: Europe/Paris
    networks:
      - proxy

# volumes:
#   radarr_data:
#   sonarr_data:
#   transmission_data:
#   jackett_data:
#   jellyseerr_data:

networks:
  proxy:
    external: true