################################################################################
# MEDIA STACK => docker stack deploy -c stacks/media/stack.yaml media
################################################################################

version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.1
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.jellyfin.loadbalancer.server.port=8096
        - traefik.http.routers.jellyfin.rule=Host(`jellyfin.lsarlinmagnus.fr`)
        - traefik.http.routers.jellyfin.entrypoints=websecure
        - traefik.http.routers.jellyfin.tls=true
        - traefik.http.routers.jellyfin.tls.certresolver=ovh
        # - traefik.http.routers.jellyfin.middlewares=authelia@file
        - homepage.group=Media
        - homepage.name=Jellyfin
        - homepage.icon=jellyfin.png
        - homepage.href=https://jellyfin.lsarlinmagnus.fr
        - homepage.widget.type=jellyfin
        - homepage.widget.url=https://jellyfin.lsarlinmagnus.fr
        - homepage.widget.key=${JELLYFIN_HP_API_TOKEN}
        - homepage.widget.enableBlocks=true
        - homepage.widget.enableNowPlaying=true
        - homepage.widget.fields=["movies", "series", "episodes"]
    environment:
      TZ: Europe/Paris
    volumes:
      - /media/raid/jellyfin/media/audiobooks:/data/audiobooks
      - /media/raid/jellyfin/media/movies:/data/movies
      - /media/raid/jellyfin/media/series:/data/series
      - jellyfin_config:/config
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    # # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1000:1000
    # ports:
    #   - 3010:8096/tcp
    #   - 3011:7359/udp
    networks:
      - proxy

volumes:
  jellyfin_config:

networks:
  proxy:
    external: true