################################################################################
# ADMIN STACK => docker stack deploy -c stacks/core/sablier/stack.yaml sablier
################################################################################

version: '3.8'

services:
  sablier:
    image: sablierapp/sablier:1.11.1
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        # whoami
        traefik.http.middlewares.whoami.plugin.sablier.group: whoami
        traefik.http.middlewares.whoami.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.whoami.plugin.sablier.sessionDuration: 1m
        traefik.http.middlewares.whoami.plugin.sablier.dynamic.displayName: whoami
        # seerr
        traefik.http.middlewares.seerr.plugin.sablier.group: seerr
        traefik.http.middlewares.seerr.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.seerr.plugin.sablier.sessionDuration: 10m
        traefik.http.middlewares.seerr.plugin.sablier.dynamic.displayName: seerr
        # papra
        traefik.http.middlewares.papra.plugin.sablier.group: papra
        traefik.http.middlewares.papra.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.papra.plugin.sablier.sessionDuration: 10m
        traefik.http.middlewares.papra.plugin.sablier.dynamic.displayName: papra
        # omnitools
        traefik.http.middlewares.omnitools.plugin.sablier.group: omnitools
        traefik.http.middlewares.omnitools.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.omnitools.plugin.sablier.sessionDuration: 10m
        traefik.http.middlewares.omnitools.plugin.sablier.dynamic.displayName: omnitools
        # whatsupdocker
        traefik.http.middlewares.whatsupdocker.plugin.sablier.group: whatsupdocker
        traefik.http.middlewares.whatsupdocker.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.whatsupdocker.plugin.sablier.sessionDuration: 10m
        traefik.http.middlewares.whatsupdocker.plugin.sablier.dynamic.displayName: whatsupdocker
        #
        traefik.http.services.sablier.loadbalancer.server.port: 10000
        homepage.group: Core
        homepage.name: Sablier
        homepage.icon: sh-sablier.png
    command:
      - start
      - --provider.name=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SABLIER_STRATEGY_DYNAMIC_DEFAULT_THEME: ghost
      TZ: Europe/Paris
    networks:
      - proxy

networks:
  proxy:
    external: true