site_name: Documentation and journey of my homelab
site_url: https://louisonsarlinmagnus.github.io/homelab
repo_url: https://github.com/louisonsarlinmagnus/homelab
repo_name: homelab

nav:
  - Welcome to my homelab project: index.md
  - Cheatsheet Markdown:
      - cheatsheet/index.md
      - Generic formatting: cheatsheet/generic_formatting.md
      - Links and images: cheatsheet/links_and_images.md
      - Diagrams: cheatsheet/diagrams.md
      - Tables: cheatsheet/tables.md
      - Superfences and tabs: cheatsheet/superfences_and_tabs.md
      - Maths: cheatsheet/maths.md
  - Blog:
    - blog/index.md

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: lime
  icon:
    repo: fontawesome/brands/github
    tag:
      testID: material/test-tube
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
plugins:
- search
- blog:
    blog_toc: true
    authors: true
    authors_file: blog/.authors.yaml
    post_excerpt: required
- tags
extra:
  tags:
    test: testID
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/louisonsm/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      baselevel: "3"
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  # - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css