################################################################################
# CORE STACK => docker stack deploy -c stacks/core/stack.yaml core
################################################################################

version: '3.8'

services:
  # gotify:
  #   image: gotify/server
  #   deploy:
  #     replicas: 1
  #     labels:
  #       - homepage.group=Core
  #       - homepage.name=Gotify
  #       - homepage.icon=gotify.png
  #       # - homepage.href=https://gotify.${DOMAIN_NAME}
  #   ports:
  #     - 3001:80
  #   volumes:
  #     - gotify_data:/app/data
  #     - ./config/gotify/gotify.yaml:/etc/gotify/config.yml
  #   networks:
  #     - proxy

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.homepage.loadbalancer.server.port=3000
        - traefik.http.routers.homepage.rule=Host(`homepage.lsarlinmagnus.fr`)
        - traefik.http.routers.homepage.entrypoints=websecure
        - traefik.http.routers.homepage.tls=true
        - traefik.http.routers.homepage.tls.certresolver=ovh
        - traefik.http.routers.homepage.middlewares=authelia@file
        - homepage.group=Core
        - homepage.name=Homepage
        - homepage.icon=homepage.png
        - homepage.href=https://homepage.lsarlinmagnus.fr
    configs:
      - source: homepage_bookmarks
        target: /app/config/bookmarks.yaml
      - source: homepage_docker
        target: /app/config/docker.yaml
      - source: homepage_services
        target: /app/config/services.yaml
      - source: homepage_settings
        target: /app/config/settings.yaml
      - source: homepage_widgets
        target: /app/config/widgets.yaml
      - source: homepage_wallpaper
        target: /app/public/images/wallpaper.jpg
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.lsarlinmagnus.fr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /media/raid:/media/raid
      - /mnt/backup:/mnt/backup
    networks:
      - proxy
  
configs:
  homepage_bookmarks:
    file: ./config/homepage/config/bookmarks.yaml
  homepage_docker:
    file: ./config/homepage/config/docker.yaml
  homepage_services:
    file: ./config/homepage/config/services.yaml
  homepage_settings:
    file: ./config/homepage/config/settings.yaml
  homepage_widgets:
    file: ./config/homepage/config/widgets.yaml
  homepage_wallpaper:
    file: ./config/homepage/wallpaper/wallpaper.jpg

  # watchtower:
  #   image: containrrr/watchtower:latest 
  #   deploy:
  #     replicas: 1
  #     labels:
  #       - homepage.group=Core
  #       - homepage.name=Watchtower
  #       - homepage.icon=watchtower.png
  #       - homepage.widget.type=watchtower
  #       - homepage.widget.url=http://watchtower:8080
  #       - homepage.widget.key=changeme
  #       - homepage.widget.fields=["containers_scanned", "containers_updated", "containers_failed"]
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     TZ: Europe/Paris
  #     WATCHTOWER_DEBUG: "true"
  #     WATCHTOWER_CLEANUP: "true"
  #     WATCHTOWER_SCHEDULE: "0 30 6 * * *"
  #     WATCHTOWER_LABEL_ENABLE: "true"
  #     # WATCHTOWER_NOTIFICATIONS: gotify
  #     # WATCHTOWER_NOTIFICATION_GOTIFY_URL: https://gotify.${DOMAIN_NAME}
  #     # WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN :changeme
  #     # WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY: "true"
  #     WATCHTOWER_HTTP_API_METRICS: "true"
  #     WATCHTOWER_HTTP_API_TOKEN: changeme
  #   networks:
  #     - overlay_net

volumes:
  gotify_data:

networks:
  proxy:
    external: true