################################################################################
# CORE STACK => docker stack deploy -c stacks/core/stack.yaml core
################################################################################

version: '3.8'

services:
  gotify:
    image: gotify/server:2.8.0 
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.gotify.loadbalancer.server.port: 80
        traefik.http.routers.gotify.rule: Host(`gotify.lsarlinmagnus.fr`)
        traefik.http.routers.gotify.entrypoints: websecure
        traefik.http.routers.gotify.tls: "true"
        traefik.http.routers.gotify.tls.certresolver: ovh
        homepage.group: Core
        homepage.name: Gotify
        homepage.icon: gotify.png
        homepage.href: https://gotify.lsarlinmagnus.fr
    env_file:
      - ./gotify/.env
      - ./gotify/.env.secret
    environment:
      TZ: Europe/Paris
    volumes:
      - gotify_data:/app/data
    networks:
      - proxy

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.9.0
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.homepage.loadbalancer.server.port: 3000
        traefik.http.routers.homepage.rule: Host(`homepage.lsarlinmagnus.fr`)
        traefik.http.routers.homepage.entrypoints: websecure
        traefik.http.routers.homepage.tls: "true"
        traefik.http.routers.homepage.tls.certresolver: ovh
        traefik.http.routers.homepage.middlewares: authelia@file
        homepage.group: Core
        homepage.name: Homepage
        homepage.icon: homepage.png
        homepage.href: https://homepage.lsarlinmagnus.fr
    configs:
      - source: homepage_bookmarks
        target: /app/config/bookmarks.yaml
      - source: homepage_docker
        target: /app/config/docker.yaml
      - source: homepage_services
        target: /app/config/services.yaml
      - source: homepage_settings
        target: /app/config/settings.yaml
      - source: homepage_widgets
        target: /app/config/widgets.yaml
      - source: homepage_wallpaper
        target: /app/public/images/wallpaper.jpg
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.lsarlinmagnus.fr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /media/raid:/media/raid:ro
      # - /mnt/backup:/mnt/backup
    networks:
      - proxy

  diun:
    image: crazymax/diun:4.31.0
    deploy:
      replicas: 1
      labels:
        homepage.group: Core
        homepage.name: DIUN
        homepage.icon: diun.png
    environment:  
      DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT: "true"
      DIUN_WATCH_WORKERS: 10
      DIUN_WATCH_SCHEDULE: 0 */1 * * *
      DIUN_WATCH_JITTER: 30s
      DIUN_DEFAULTS_NOTIFYON: new,update
      DIUN_DEFAULTS_INCLUDETAGS: ^\d+\.\d+\.\d+$$,^v\d+\.\d+\.\d+$$
      DIUN_PROVIDERS_SWARM: "true"
      DIUN_PROVIDERS_DOCKER: "true"
      LOG_LEVEL: debug
      LOG_JSON: "false"
      DIUN_NOTIF_GOTIFY_ENDPOINT: http://gotify:80
      DIUN_NOTIF_GOTIFY_TOKEN: AkV3e0.jplEvMnv
      DIUN_NOTIF_GOTIFY_TEMPLATETITLE: 
      DIUN_NOTIF_GOTIFY_TEMPLATEBODY: 
      TZ: Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

configs:
  homepage_bookmarks:
    file: ./homepage/config/bookmarks.yaml
  homepage_docker:
    file: ./homepage/config/docker.yaml
  homepage_services:
    file: ./homepage/config/services.yaml
  homepage_settings:
    file: ./homepage/config/settings.yaml
  homepage_widgets:
    file: ./homepage/config/widgets.yaml
  homepage_wallpaper:
    file: ./homepage/wallpaper/wallpaper.jpg

volumes:
  gotify_data:

networks:
  proxy:
    external: true