################################################################################
# ADMIN STACK => docker stack deploy -c stacks/admin/sablier/stack.yaml sablier
################################################################################

version: '3.8'

services:
  sablier:
    image: sablierapp/sablier:1.11.1
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        # whoami
        traefik.http.middlewares.whoami.plugin.sablier.group: whoami
        traefik.http.middlewares.whoami.plugin.sablier.sablierUrl: http://sablier:10000
        traefik.http.middlewares.whoami.plugin.sablier.sessionDuration: 1m
        traefik.http.middlewares.whoami.plugin.sablier.dynamic.displayName: whoami
        traefik.http.services.sablier.loadbalancer.server.port: 10000
        homepage.group: Administration
        homepage.name: Sablier
        homepage.icon: sh-sablier.png
    command:
      - start
      - --provider.name=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SABLIER_STRATEGY_DYNAMIC_DEFAULT_THEME: ghost
      TZ: Europe/Paris
    networks:
      - proxy

  whoami:
    image: traefik/whoami:v1.11.0
    deploy:
      labels:
        sablier.enable: "true"
        sablier.group: whoami
        traefik.enable: "true"
        traefik.swarm.lbswarm: "true"
        traefik.http.routers.whoami.middlewares: whoami@swarm
        traefik.http.services.whoami.loadbalancer.server.port: 80
        traefik.http.routers.whoami.rule: Host(`new.lsarlinmagnus.fr`)
        traefik.http.routers.whoami.entrypoints: websecure
        traefik.http.routers.whoami.tls: "true"
        traefik.http.routers.whoami.tls.certresolver: ovh
        homepage.group: Administration
        homepage.name: Whoami
        homepage.icon: traefik.png
        homepage.href: https://new.lsarlinmagnus.fr
    networks:
      - proxy

networks:
  proxy:
    external: true