################################################################################
# ADMIN STACK => docker stack deploy -c stacks/admin/sablier/stack.yaml sablier
################################################################################

version: '3.8'

services:
  sablier:
    image: sablierapp/sablier:1.11.1
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.sablier.loadbalancer.server.port: 10000
        homepage.group: Administration
        homepage.name: Sablier
        homepage.icon: sh-sablier.png
    command:
      - start
      - --provider.name=swarm
    configs:
      - source: sablier_config
        target: /etc/sablier/sablier.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Paris
    ports:
      - 10000:10000
    networks:
      - proxy

  whoami:
    image: traefik/whoami:v1.11.0
    deploy:
      replicas: 0
      labels:
        traefik.enable: "true"
        traefik.swarm.lbswarm: "true"
        traefik.http.routers.whoami.middlewares: sablier@file
        traefik.http.routers.whoami.service: whoami
        sablier.enbale: "true"
        sablier.group: mygroup
        traefik.http.services.whoami.loadbalancer.server.port: 80
        traefik.http.routers.whoami-https.rule: Host(`new.lsarlinmagnus.fr`)
        traefik.http.routers.whoami-https.entrypoints: websecure
        traefik.http.routers.whoami-https.tls: "true"
        traefik.http.routers.whoami-https.tls.certresolver: ovh
        # traefik.http.routers.whoami-https.middlewares: authelia@file
        homepage.group: Administration
        homepage.name: Whoami
        homepage.icon: traefik.png
        homepage.href: https://new.lsarlinmagnus.fr
    networks:
      - proxy

configs:
  sablier_config:
    file: ./sablier.yaml

networks:
  proxy:
    external: true