################################################################################
# PAPRA STACK => docker stack deploy -c stacks/papra/stack.yaml papra
################################################################################

version: '3.8'

services:

  papra:
    image: ghcr.io/papra-hq/papra:26.1.0-rootless
    deploy:
      replicas: 1
      labels:
        sablier.enable: "true"
        sablier.group: papra
        traefik.enable: "true"
        traefik.swarm.lbswarm: "true"
        traefik.http.routers.papra.middlewares: papra@swarm
        traefik.http.services.papra.loadbalancer.server.port: 1221
        traefik.http.routers.papra.rule: Host(`papra.lsarlinmagnus.fr`)
        traefik.http.routers.papra.entrypoints: websecure
        traefik.http.routers.papra.tls: "true"
        traefik.http.routers.papra.tls.certresolver: ovh
        # traefik.http.routers.papra.middlewares: authelia@file
        homepage.group: Documents
        homepage.name: Papra
        homepage.icon: papra.png
        homepage.href: https://papra.lsarlinmagnus.fr
    env_file:
      - ./.env.secret
    environment:
      APP_BASE_URL: https://papra.lsarlinmagnus.fr
      DOCUMENTS_OCR_LANGUAGES: fra
    volumes:
      - papra_data:/app/app-data
      - /media/raid/papra/documents:/app/app-data/documents
    networks:
      - proxy

volumes:
  papra_data:

networks:
  proxy:
    external: true