################################################################################
# ADMIN STACK => docker stack deploy -c stacks/admin/stack.yaml admin
################################################################################

version: '3.8'

services:

  traefik:
    image: traefik:ramequin
    deploy:
      replicas: 1
      labels:
        - homepage.group=Administration
        - homepage.name=Traefik
        - homepage.icon=traefik.png
        - homepage.href=http://localhost:80/
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs_data:/var/traefik/certs/:rw
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yaml
      - source: traefik_middlewares
        target: /etc//traefik/files/middlewares.yaml
      - source: traefik_routers
        target: /etc//traefik/files/routers.yaml
      - source: traefik_services
        target: /etc//traefik/files/services.yaml
    secrets:
      - ovh_endpoint
      - ovh_application_key
      - ovh_application_secret
      - ovh_consumer_key
    environment:
      TZ: Europe/Paris
      OVH_ENDPOINT_FILE: /run/secrets/ovh_endpoint
      OVH_APPLICATION_KEY_FILE: /run/secrets/ovh_application_key
      OVH_APPLICATION_SECRET_FILE: /run/secrets/ovh_application_secret
      OVH_CONSUMER_KEY_FILE: /run/secrets/ovh_consumer_key
    networks:
      - proxy

  whoami:
    image: traefik/whoami:v1.11.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.services.whoami.loadbalancer.server.port=80
        - traefik.http.routers.whoami-https.rule=Host(`new.lsarlinmagnus.fr`)
        - traefik.http.routers.whoami-https.entrypoints=websecure
        - traefik.http.routers.whoami-https.tls=true
        - traefik.http.routers.whoami-https.tls.certresolver=ovh
    networks:
      - proxy

configs:
  traefik_config:
    file: ./config/traefik/traefik.yaml
  traefik_middlewares:
    file: ./config/traefik/files/middlewares.yaml
  traefik_routers:
    file: ./config/traefik/files/routers.yaml
  traefik_services:
    file: ./config/traefik/files/services.yaml

secrets:
  ovh_endpoint:
    file: ./config/traefik/secrets/ovh_endpoint.secret
  ovh_application_key:
    file: ./config/traefik/secrets/ovh_application_key.secret
  ovh_application_secret:
    file: ./config/traefik/secrets/ovh_application_secret.secret
  ovh_consumer_key:
    file: ./config/traefik/secrets/ovh_consumer_key.secret

networks:
  proxy:
    driver: overlay
    attachable: true
    name: proxy

volumes:
  traefik_certs_data:

  # authelia:
  #   image: authelia/authelia:latest
  #   deploy:
  #     replicas: 1
  #     labels:
  #       # - traefik.enable=true
  #       # - traefik.http.routers.authelia.entrypoints=websecure
  #       # - traefik.http.routers.authelia.rule=Host(`${AUTHELIA_URL}`)
  #       # - traefik.http.routers.authelia.tls=true
  #       # - traefik.http.routers.authelia.tls.certresolver=myresolver
  #       - homepage.group=Administration
  #       - homepage.name=Authelia
  #       - homepage.icon=authelia.png
  #       - homepage.href=http://localhost:2999/
  #   volumes:
  #     - .config/authelia:/config
  #   ports:
  #     - 2999:9091
  #   environment:
  #     TZ: Europe/Paris
  #   networks:
  #     - overlay_net

  # crowdsec:
  #   image: crowdsecurity/crowdsec
  #   deploy:
  #     replicas: 1
  #   volumes:
  #     - ./crowdsec_data:/var/lib/crowdsec/data
  #   networks:
  #     - overlay_net

  # lldap:
  #   image: nitnelave/lldap:stable
  #   deploy:
  #     replicas: 1
  #     labels:
  #       - homepage.group=Administration
  #       - homepage.name=LLDAP
  #       - homepage.icon=mdi-account-group
  #       - homepage.href=http://localhost:17170/
  #   volumes:
  #     - ./lldap_data:/data
  #   ports:
  #     - 17170:17170
  #     - 389:389
  #   environment:
  #     UID: 1000
  #     GID: 1000
  #     LLDAP_JWT_SECRET: ${LLDAP_JWZ_SECRET}
  #     LLDAP_LDAP_USER_PASS: ${LLDAP_USER_PASS}
  #     LLDAP_LDAP_BASE_DN: dc=lsarlinmagnus,dc=fr
  #     TZ: Europe/Paris
  #   networks:
  #     - overlay_net
