---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - OVH:
        - icon: ovh.png
          href: https://www.ovh.com/manager/web/#/domain/lsarlinmagnus.fr/information
    - Github:
        - icon: github-light.png
          href: https://github.com/louisonsarlinmagnus/

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/
    - Twitch:
        - icon: twitch.png
          href: https://www.twitch.tv/
