################################################################################
# CORE STACK => docker stack deploy -c stacks/core/gotify/stack.yaml gotify
################################################################################

version: '3.8'

services:
  gotify:
    image: gotify/server:2.9.0 
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.gotify.loadbalancer.server.port: 80
        traefik.http.routers.gotify.rule: Host(`gotify.lsarlinmagnus.fr`)
        traefik.http.routers.gotify.entrypoints: websecure
        traefik.http.routers.gotify.tls: "true"
        traefik.http.routers.gotify.tls.certresolver: ovh
        homepage.group: Core
        homepage.name: Gotify
        homepage.icon: gotify.png
        homepage.href: https://gotify.lsarlinmagnus.fr
    env_file:
      - ./.env
      - ./.env.secret
    environment:
      TZ: Europe/Paris
    volumes:
      - /media/raid/gotify:/app/data
    networks:
      - proxy

volumes:
  gotify_data:

networks:
  proxy:
    external: true