################################################################################
# HOME ASSISTANT STACK => docker compose -f stacks/home_automation/homeassistant/homeassistant.yaml up -d
################################################################################

services:

  homeassistant:
    image: homeassistant/home-assistant:2026.2
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      traefik.http.routers.homeassistant.rule: Host(`homeassistant.lsarlinmagnus.fr`)
      traefik.http.routers.homeassistant.entrypoints: websecure
      traefik.http.routers.homeassistant.tls: true
      traefik.http.routers.homeassistant.tls.certresolver: ovh
      homepage.group: Home Automation
      homepage.name: Home Assistant
      homepage.icon: home-assistant.png
      homepage.href: https://homeassistant.lsarlinmagnus.fr/auth/oidc/redirect
      homepage.widget.type: homeassistant
      homepage.widget.url: http://homeassistant:8123
      homepage.widget.key: ${HOMEASSISTANT_HOMEPAGE_API_KEY}
      homepage.widget.fields: '["people_home", "lights_on", "switches_on"]'
    environment:
      TZ: Europe/Paris
    volumes:
      - config:/config
    networks:
      - proxy

  matter_server:
    image: ghcr.io/matter-js/python-matter-server:8.1.2
    labels:
      homepage.group: Home Automation
      homepage.name: Matter Server
      homepage.icon: matter.png
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    environment:
      - MATTER_SERVER_PORT=5580
      - MATTER_SERVER_LOG_LEVEL=info
    ports:
      - 5580:5580
    # security_opt:
    #   # Needed for Bluetooth via dbus
    #   - apparmor:unconfined
    # volumes:
      # Create an .env file that sets the USERDIR environment variable.
      # - ${USERDIR:-$HOME}/docker/matter-server/data:/data/
      # Required for Bluetooth via D-Bus
      # - /run/dbus:/run/dbus:ro
    # If you adjust command line, make sure to pass the default CMD arguments too:
    #command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0

volumes:
  config:

networks:
  proxy:
    external: true