################################################################################
# WEDDING SHARE
################################################################################

version: '3.8'

services:
  wedding-share:
    image: cirx08/wedding_share:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - target: 5000
        published: 8080
        protocol: tcp
        mode: host
    environment:
      TITLE: Marie et Louison
      ACCOUNT_ADMIN_USERNAME: admin
      ACCOUNT_ADMIN_PASSWORD: admin
      DATABASE_TYPE: sqlite
      ENCRYPTION_KEY: ChangeMe
      ENCRYPTION_SALT: ChangeMe
      BASE_URL: 
      LOGO: 
      SINGLE_GALLERY_MODE:
      GALLERY_BANNER_IMAGE:
      GALLERY_QUOTE:
      

    volumes:
      - data-volume-config:/app/config
      - data-volume-thumbnails:/app/wwwroot/thumbnails
      - data-volume-uploads:/app/wwwroot/uploads
      - data-volume-custom-resources:/app/wwwroot/custom_resources
    networks:
      - pictures_net

volumes:
  data-volume-config:
    name: WeddingShare-Config
  data-volume-thumbnails:
    name: WeddingShare-Thumbnails
  data-volume-uploads:
    name: WeddingShare-Uploads
  data-volume-custom-resources:
    name: WeddingShare-CustomResources