################################################################################
# MISCELLANEOUS STACK => docker stack deploy -c stacks/services/vaultwarden/stack.yaml vaultwarden
################################################################################

version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:1.35.2
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.vaultwarden.loadbalancer.server.port: 80
        traefik.http.routers.vaultwarden.rule: Host(`mdp.lsarlinmagnus.fr`)
        traefik.http.routers.vaultwarden.entrypoints: websecure
        traefik.http.routers.vaultwarden.tls: "true"
        traefik.http.routers.vaultwarden.tls.certresolver: ovh
        homepage.group: Passwords
        homepage.name: Vaultwarden
        homepage.icon: bitwarden.png
        homepage.href: https://mdp.lsarlinmagnus.fr
    env_file:
      - ./.env.secret
    environment:
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      LOG_LEVEL: info
      TZ: Europe/Paris
    volumes:
      - /media/raid/vaultwarden:/data
    networks:
      - proxy

networks:
  proxy:
    external: true