services:
  traefik:
    image: traefik:chaource
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 30s
    command:
      # API SETTINGS
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      # ENTRYPOINTS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls= true
      # CERTIFICATE RESOLVERS
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=certificates_provider_email_address
      - --certificatesresolvers.myresolver.acme.storage=/acme_data/acme.json
      # PROVIDERS
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      # LOGGING SETTINGS
      - --log=true
      - --log.format=common
      - --log.level=INFO # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accesslog.format=common
      # MIDDLEWARES
      # FAIL2BAN
      - --http.middlewares.my-fail2ban.plugin.fail2ban.logLevel=INFO
      - --http.middlewares.my-fail2ban.plugin.fail2ban.bantime=3h
      - --http.middlewares.my-fail2ban.plugin.fail2ban.findtime=3m
      - --http.middlewares.my-fail2ban.plugin.fail2ban.maxretry=3
      - --http.middlewares.my-fail2ban.plugin.fail2ban.enabled=true
      # AUTHELIA
      - --http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN_NAME}/
      - --http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - --http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable:true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - homepage.group=Administration
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.href=https://traefik.${DOMAIN_NAME}
    environment:
      - TZ=${TIMEZONE}
    secrets:
      - certificates_provider_email_address