################################################################################
# PICTURES STACK => docker stack deploy -c stacks/pictures/stack.yaml pictures
################################################################################

version: '3.8'

services:
  immich_machine_learning:
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    deploy:
      replicas: 1
      labels:
        homepage.group: Pictures
        homepage.name: Immich-Machine-Learning
        homepage.icon: immich.png
    volumes:
      - immich_model_cache:/cache
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    healthcheck:
      disable: false
    networks:
      - proxy

  immich_postgresql:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    deploy:
      replicas: 1
      labels:
        homepage.group: Pictures
        homepage.name: Immich Postgres
        homepage.icon: postgres.png
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich_database:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      disable: false
    networks:
      - proxy

  immich_valkey:
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    deploy:
      replicas: 1
      labels:
        homepage.group: Pictures
        homepage.name: Immich Valkey
        homepage.icon: valkey.png
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - proxy

  immich:
    image: ghcr.io/immich-app/immich-server:v2.4.1
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.immich.loadbalancer.server.port: 2283
        traefik.http.routers.immich.rule: Host(`immich.lsarlinmagnus.fr`)
        traefik.http.routers.immich.entrypoints: websecure
        traefik.http.routers.immich.tls: "true"
        traefik.http.routers.immich.tls.certresolver: ovh
        # traefik.http.routers.immich.middlewares: authelia@file
        homepage.group: Pictures
        homepage.name: Immich
        homepage.icon: immich.png
        homepage.href: https://immich.lsarlinmagnus.fr
        homepage.widget.type: immich
        homepage.widget.url: https://immich.lsarlinmagnus.fr
        homepage.widget.key: ib975tH9Rvrll9TtUHfSheq9ygK5xczo4DT9idXBFc
        homepage.widget.version: 2
        homepage.widget.fields: '["users" ,"photos", "videos", "storage"]'
    volumes:
      - /media/raid/immich:/data
    environment:
      DB_PASSWORD: changeme
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich_postgresql
      REDIS_HOSTNAME: immich_valkey
      UPLOAD_LOCATION: ./library
      TZ: Europe/Paris
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    healthcheck:
      disable: false
    networks:
      - proxy

volumes:
  immich_model_cache:
  immich_database:

networks:
  proxy:
    external: true