################################################################################
# MONITORING STACK => docker stack deploy -c stacks/monitoring/stack.yaml monitoring
################################################################################

version: '3.8'

services:

  dozzle:
    image: amir20/dozzle:v8.14.12
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.dozzle.loadbalancer.server.port: 8080
        traefik.http.routers.dozzle.rule: Host(`dozzle.lsarlinmagnus.fr`)
        traefik.http.routers.dozzle.entrypoints: websecure
        traefik.http.routers.dozzle.tls: "true"
        traefik.http.routers.dozzle.tls.certresolver: ovh
        traefik.http.routers.dozzle.middlewares: authelia@file
        homepage.group: Monitoring
        homepage.name: Dozzle
        homepage.icon: dozzle.png
        homepage.href: https://dozzle.lsarlinmagnus.fr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: homelab
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_MODE: swarm
    networks:
      - proxy

  grafana:
    image: grafana/grafana:12.3.0
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        traefik.http.routers.grafana.rule: Host(`grafana.lsarlinmagnus.fr`)
        traefik.http.routers.grafana.entrypoints: websecure
        traefik.http.routers.grafana.tls: "true"
        traefik.http.routers.grafana.tls.certresolver: ovh
        homepage.group: Monitoring
        homepage.name: Grafana
        homepage.icon: grafana.png
        homepage.href: https://grafana.lsarlinmagnus.fr
    configs:
      - source: grafana_datasource_config
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    env_file:
      - ./grafana/.env
      - ./grafana/.env.secret
    environment:
      TZ: Europe/Paris
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy

  prometheus:
    image: prom/prometheus:v3.5.0
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.prometheus.loadbalancer.server.port: 9090
        traefik.http.routers.prometheus.rule: Host(`prometheus.lsarlinmagnus.fr`)
        traefik.http.routers.prometheus.entrypoints: websecure
        traefik.http.routers.prometheus.tls: "true"
        traefik.http.routers.prometheus.tls.certresolver: ovh
        traefik.http.routers.prometheus.middlewares: authelia@file
        homepage.group: Monitoring
        homepage.name: Prometheus
        homepage.icon: prometheus.png
        homepage.href: https://prometheus.lsarlinmagnus.fr
    command: --web.enable-remote-write-receiver
    configs: 
      - source: prometheus_config
        target: /prometheus/prometheus.yml
    networks:
      - proxy

  loki:
    image: grafana/loki:3.6.3
    deploy:
      replicas: 1
      labels:
        homepage.group: Monitoring
        homepage.name: Loki
        homepage.icon: loki.png
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    ports:
      - 3100:3100
    networks:
      - proxy

  alloy:
    image: grafana/alloy:v1.12.2
    deploy:
      replicas: 1
    labels:
        traefik.enable: "true"
        traefik.http.services.alloy.loadbalancer.server.port: 12345
        traefik.http.routers.alloy.rule: Host(`alloy.lsarlinmagnus.fr`)
        traefik.http.routers.alloy.entrypoints: websecure
        traefik.http.routers.alloy.tls: "true"
        traefik.http.routers.alloy.tls.certresolver: ovh
        traefik.http.routers.alloy.middlewares: authelia@file
        homepage.group: Monitoring
        homepage.name: Alloy
        homepage.icon: alloy.png
        homepage.href: https://alloy.lsarlinmagnus.fr
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    volumes:
      - /usr/share/GeoLite2/GeoLite2-City.mmdb:/usr/share/GeoLite2/GeoLite2-City.mmdb:ro
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro    
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - proxy

configs:
  prometheus_config:
    file: ./prometheus/prometheus.yaml
  grafana_datasource_config:
    file: ./grafana/datasources.yaml
  loki_config:
    file: ./loki/local-config.yaml
  alloy_config:
    file: ./alloy/config.alloy


  # uptime_kuma:
  #   image: jamiequigley/oliveTin
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

volumes:
  grafana_data:

networks:
  proxy:
    external: true
