################################################################################
# MONITORING STACK => docker stack deploy -c stacks/monitoring/stack.yaml monitoring
################################################################################

version: '3.8'

services:

  dozzle:
    image: amir20/dozzle:v8.14.12
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
        - traefik.http.routers.dozzle.rule=Host(`dozzle.lsarlinmagnus.fr`)
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls=true
        - traefik.http.routers.dozzle.tls.certresolver=ovh
        - traefik.http.routers.dozzle.middlewares=authelia@file
        - homepage.group=Monitoring
        - homepage.name=Dozzle
        - homepage.icon=dozzle.png
        - homepage.href=https://dozzle.lsarlinmagnus.fr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: homelab
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_MODE: swarm
    networks:
      - proxy

  grafana:
    image: grafana/grafana:12.3.0
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.rule=Host(`grafana.lsarlinmagnus.fr`)
        - traefik.http.routers.grafana.entrypoints=websecure
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=ovh
        - homepage.group=Monitoring
        - homepage.name=Grafana
        - homepage.icon=grafana.png
        - homepage.href=https://grafana.lsarlinmagnus.fr
    configs:
      - source: grafana_datasource_config
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    env_file:
      - ./grafana/.env
      - ./grafana/.env.secret
    environment:
      TZ: Europe/Paris
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy

  prometheus:
    image: prom/prometheus:v3.5.0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
        - traefik.http.routers.prometheus.rule=Host(`prometheus.lsarlinmagnus.fr`)
        - traefik.http.routers.prometheus.entrypoints=websecure
        - traefik.http.routers.prometheus.tls=true
        - traefik.http.routers.prometheus.tls.certresolver=ovh
        - traefik.http.routers.prometheus.middlewares=authelia@file
        - homepage.group=Monitoring
        - homepage.name=Prometheus
        - homepage.icon=prometheus.png
        - homepage.href=https://prometheus.lsarlinmagnus.fr
    configs: 
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - proxy

  node-exporter:
    image: prom/node-exporter:v1.10.2
    deploy:
      replicas: 1
      labels:
        - homepage.group=Monitoring
        - homepage.name=Node-Exporter
        - homepage.icon=prometheus.png
    networks:
      - proxy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.cadvisor.loadbalancer.server.port=8080
        - traefik.http.routers.cadvisor.rule=Host(`cadvisor.lsarlinmagnus.fr`)
        - traefik.http.routers.cadvisor.entrypoints=websecure
        - traefik.http.routers.cadvisor.tls=true
        - traefik.http.routers.cadvisor.tls.certresolver=ovh
        - traefik.http.routers.cadvisor.middlewares=authelia@file
        - homepage.group=Monitoring
        - homepage.name=CAdvisor
        - homepage.icon=cadvisor.png
        - homepage.href=https://cadvisor.lsarlinmagnus.fr
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --disable_metrics=diskIO,process,disk,hugetlb,resctrl,udp,advtcp,tcp,referenced_memory
      - --housekeeping_interval=55s
      - --docker_only
    networks:
      - proxy

configs:
  prometheus_config:
    file: ./prometheus/prometheus.yaml
  grafana_datasource_config:
    file: ./grafana/datasources.yaml

  # fail2ban_exporter:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # loki:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # promtail:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # uptime_kuma:
  #   image: jamiequigley/oliveTin
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

volumes:
  grafana_data:

networks:
  proxy:
    external: true
