################################################################################
# MONITORING STACK => docker stack deploy -c stacks/monitoring/stack.yaml monitoring
################################################################################

version: '3.8'

services:
  # cadvisor:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  dozzle:
    image: amir20/dozzle
    deploy:
      labels:
        - homepage.group=Monitoring
        - homepage.name=Dozzle
        - homepage.icon=dozzle.png
        - homepage.href=http://localhost:3003/
        # - homepage.href=https://dozzle.${DOMAIN_NAME}
        - traefik.enable=true
        - traefik.http.services.dozzle.loadbalancer.server.port=8080
        - traefik.http.routers.dozzle.rule=Host(`dozzle.lsarlinmagnus.fr`)
        - traefik.http.routers.dozzle.entrypoints=websecure
        - traefik.http.routers.dozzle.tls=true
        - traefik.http.routers.dozzle.tls.certresolver=ovh
        - traefik.http.routers.dozzle.middlewares=authelia@file

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_HOSTNAME: homelab
      DOZZLE_ENABLE_ACTIONS: "true"
      DOZZLE_MODE: swarm
    networks:
      - proxy

  # fail2ban_exporter:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # grafana:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # loki:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # node_exporter:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # prometheus:
  #   image:
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # promtail:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy

  # uptime_kuma:
  #   image: jamiequigley/oliveTin
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - proxy


networks:
  proxy:
    external: true
