################################################################################
# MONITORING STACK => docker stack deploy -c stacks/monitoring/stack.yaml monitoring
################################################################################

version: '3.8'

services:
  # cadvisor:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  dozzle:
    image: amir20/dozzle
    deploy:
      labels:
        - homepage.group=Monitoring
        - homepage.name=Dozzle
        - homepage.icon=dozzle.png
        - homepage.href=https://dozzle.${DOMAIN_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3003:8080
    environment:
      - DOZZLE_HOSTNAME=Turbonas
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_MODE=swarm
    networks:
      - overlay_net

  # dozzle:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # fail2ban_exporter:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # grafana:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # loki:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # node_exporter:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # prometheus:
  #   image:
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # promtail:
  #   image: 
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net

  # uptime_kuma:
  #   image: jamiequigley/oliveTin
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - overlay_net


networks:
  overlay_net:
    driver: overlay
    attachable: true